package com.voicesofwynn.core.loadmanager;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.Map;

public interface RegisterType {

    void load(FileInputStream input);

    /**
     * @param writer file writer in to which to write the generated bytes
     * @param section section is the loaded yaml part that this type owns
     */
    void write(FileOutputStream writer, Object section, Map<String, Object> variables);

    String getName();
}
